## Analysis of Top 10 Medicines

We are interested to see the "top 10" medicines use in NHS primary care in England in 2019. WE will produce the top 10 chemicals and BNF paragraphs by volume and cost.

In [1]:
import pandas as pd
import numpy as np
from ebmdatalab import bq, maps, charts

In [2]:

pd.set_option('display.float_format', lambda x: '%.2f' % x)

## Top 10 Chemicals in 2019 by Volume

In [3]:
## code for top 10 items
sql = '''
WITH
  bnf_tab AS (
  SELECT
    DISTINCT chemical,
    chemical_code
  FROM
    ebmdatalab.hscic.bnf )
SELECT
 SUBSTR(presc.bnf_code, 0, 9) AS chemical_code, ##user requested chemical substance
 chemical,
 SUM(items) AS items,
 Sum(actual_cost) AS actualcost
FROM
ebmdatalab.hscic.normalised_prescribing_standard AS presc
LEFT JOIN
bnf_tab
ON
chemical_code=SUBSTR(presc.bnf_code,0,9)
WHERE
 month BETWEEN TIMESTAMP('2019-01-01')
 AND TIMESTAMP('2019-12-01') ##user requested 2019
GROUP BY
chemical_code,
chemical
ORDER BY
 items DESC
 LIMIT 20 ##limit to 20
  '''

df_chemical_items = bq.cached_read(sql, csv_path='chemical_items.csv')
df_chemical_items.head(11)

Downloading: 100%|██████████| 20/20 [00:00<00:00, 84.83rows/s]

   chemical_code                 chemical     items  actualcost
0      0212000B0             Atorvastatin  45792988 55759286.30
1      0602010V0     Levothyroxine Sodium  32934807 62747734.83
2      0103050P0               Omeprazole  31791795 50092650.15
3      0206020A0               Amlodipine  30541931 29329631.14
4      0205051R0                 Ramipril  29318773 41931828.72
5      0103050L0             Lansoprazole  26723751 33480232.31
6      0204000H0      Bisoprolol Fumarate  24905410 21124240.45
7      0906040G0           Colecalciferol  24004981 86331206.06
8      0601022B0  Metformin Hydrochloride  22375503 84576576.83
9      0209000A0                  Aspirin  22205029 17516108.15
10     0212000Y0              Simvastatin  21804236 22692074.46

## Top 10 Chemicals in 2019 by Cost

In [5]:
sql = '''
WITH
  bnf_tab AS (
  SELECT
    DISTINCT chemical,
    chemical_code
  FROM
    ebmdatalab.hscic.bnf )
SELECT
 SUBSTR(presc.bnf_code, 0, 9) AS chemical_code, ##user requested chemical substance
 chemical,
 SUM(items) AS items,
 Sum(actual_cost) AS actualcost
FROM
ebmdatalab.hscic.normalised_prescribing_standard AS presc
LEFT JOIN
bnf_tab
ON
chemical_code=SUBSTR(presc.bnf_code,0,9)
WHERE
 month BETWEEN TIMESTAMP('2019-01-01')
 AND TIMESTAMP('2019-12-01') ##user requested 2018
GROUP BY
chemical_code,
chemical
ORDER BY
 actualcost DESC
 LIMIT 20 ##limit to 20
  '''

df_chemical_cost = bq.cached_read(sql, csv_path='chemical_cost.csv')
df_chemical_cost.head(11)

   chemical_code                           chemical     items   actualcost
0      0208020Z0                           Apixaban   5862145 268932709.57
1      090402000                  Enteral Nutrition   3725985 236304624.65
2      0302000C0         Beclometasone Dipropionate  11293617 234589521.28
3      0208020Y0                        Rivaroxaban   4310724 201973695.35
4      0601060D0     Glucose Blood Testing Reagents   6806704 147620355.28
5      0302000N0       Fluticasone Propionate (Inh)   4523933 138481006.46
6      0302000K0                         Budesonide   3585322 118720380.54
7      0301020Q0                 Tiotropium Bromide   3704740 109306933.71
8      090401000  Other Food For Special Diet Preps    888137  89162778.16
9      1404000H0                          Influenza  10193903  87512930.57
10     1001010P0                           Naproxen   6860835  86416823.45

## Top 10 Classes of Medicines in 2019 by Volume

In [7]:
sql = '''
WITH
  bnf_tab AS (
  SELECT
    DISTINCT para,
    para_code
  FROM
    ebmdatalab.hscic.bnf )
SELECT
 SUBSTR(presc.bnf_code, 0, 6) AS para_code, ##user requested chemical substance
 para,
 SUM(items) AS items,
 Sum(actual_cost) AS actualcost
FROM
ebmdatalab.hscic.normalised_prescribing_standard AS presc
LEFT JOIN
bnf_tab
ON
para_code=SUBSTR(presc.bnf_code,0,6)
WHERE
 month BETWEEN TIMESTAMP('2019-01-01')
 AND TIMESTAMP('2019-12-01') ##user requested 2019
GROUP BY
para_code,
para
ORDER BY
 items DESC
 LIMIT 20 ##limit to 20
  '''

df_para_items = bq.cached_read(sql, csv_path='para_items.csv')
df_para_items.head(11)

    para_code                                      para     items   actualcost
0       21200                    Lipid-Regulating Drugs  75997663 116388715.54
1       20505            Renin-Angiotensin System Drugs  65424446 188452348.68
2       10305                    Proton Pump Inhibitors  62236186  98727913.18
3       20602                  Calcium-Channel Blockers  42419537 104996615.48
4       60102                        Antidiabetic Drugs  41654329 545347171.64
5       40303  Selective Serotonin Re-Uptake Inhibitors  40254277  66154128.62
6       20400          Beta-Adrenoceptor Blocking Drugs  39505912  67928110.55
7       40701   Non-Opioid Analgesics And Compound Prep  34487135 128491849.94
8       20900                        Antiplatelet Drugs  33308350  66684076.62
9       60201                          Thyroid Hormones  32992875  81048503.79
10      40801                       Control Of Epilepsy  28704569 278841283.05

## Top 10 Classes of Medicines in 2019 by Cost

In [9]:
sql = '''
WITH
  bnf_tab AS (
  SELECT
    DISTINCT para,
    para_code
  FROM
    ebmdatalab.hscic.bnf )
SELECT
 SUBSTR(presc.bnf_code, 0, 6) AS para_code, ##user requested chemical substance
 para,
 SUM(items) AS items,
 Sum(actual_cost) AS actualcost
FROM
ebmdatalab.hscic.normalised_prescribing_standard AS presc
LEFT JOIN
bnf_tab
ON
para_code=SUBSTR(presc.bnf_code,0,6)
WHERE
 month BETWEEN TIMESTAMP('2019-01-01')
 AND TIMESTAMP('2019-12-01') ##user requested 2019
GROUP BY
para_code,
para
ORDER BY
 actualcost DESC
 LIMIT 20 ##limit to 20
  '''

df_para_cost = bq.cached_read(sql, csv_path='para_cost.csv')
df_para_cost.head(11)

    para_code                                     para     items   actualcost
0       30200            Corticosteroids (Respiratory)  21099043 548653646.77
1       60102                       Antidiabetic Drugs  41654329 545347171.64
2       20802                      Oral Anticoagulants  18486373 541626862.54
3       60101                                  Insulin   7538314 332531643.04
4       40801                      Control Of Epilepsy  28704569 278841283.05
5       90402                        Enteral Nutrition   3725985 236304624.65
6       40702                        Opioid Analgesics  23196389 213975882.02
7       20505           Renin-Angiotensin System Drugs  65424446 188452348.68
8       60106  Diabetic Diagnostic & Monitoring Agents   7145514 155910265.04
9       30102           Antimuscarinic Bronchodilators   5444178 153085158.06
10      70402  Drugs/Urin'y Frequ'cy Enuresis & Incont   7647001 136308280.48